data <- read.table("household_power_consumption.txt", sep=";", header=TRUE, na.strings="?", colClasses=c("character", "character", rep("numeric", 7)))
data$Time <- strptime(paste(data$Date,data$Time), "%d/%m/%Y %H:%M:%S")
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
datafeb <- subset(data, Date > '2007-01-31' & Date < '2007-02-03')
png(file='plot3.png', width=480, height=480)
with(datafeb, plot(Time, Sub_metering_1, type='l', xlab = '', ylab='Energy sub metering'))
with(datafeb, lines(Time, Sub_metering_2, col='red'))
with(datafeb, lines(Time, Sub_metering_3, col='blue'))
legend('topright', lwd=1, col=c('black', 'red', 'blue'), legend=c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'))
dev.off()
