data <- read.table("household_power_consumption.txt", sep=";", header=TRUE, na.strings="?", colClasses=c("character", "character", rep("numeric", 7)))
data$Time <- strptime(paste(data$Date,data$Time), "%d/%m/%Y %H:%M:%S")
data$Date <- as.Date(data$Date, format="%d/%m/%Y")
datafeb <- subset(data, Date > '2007-01-31' & Date < '2007-02-03')
png(file='plot2.png', width=480, height=480)
with(datafeb, plot(Time, Global_active_power, type='l', xlab = '', ylab='Global Active Power (kilowatts)'))
dev.off()
